# Funding and Treasury Information
# Seedbringer Treasury System Configuration

github: [hannesmitterer]
patreon: euystacio
custom:
  - "Bitcoin: Treasury managed through Seedbringer Council"
  - "Ethereum: Treasury managed through Seedbringer Council"
  - "https://euystacio.ai/treasury"
