# Monitoring Workflow for Protocollo Meta Salvage
# This workflow defines the continuous monitoring pipeline using Kafka, Flink, and Prometheus
# for real-time risk identification and metric collection from CaaS providers.

apiVersion: v1
kind: Workflow
metadata:
  name: meta-salvage-monitoring
  namespace: euystacio-ai
  labels:
    component: protocollo-meta-salvage
    layer: monitoring

spec:
  description: >
    Continuous monitoring and risk identification workflow for Protocollo Meta Salvage.
    Collects metrics from CaaS providers, analyzes Symbiosis Scores, and triggers
    alerts when ethical risks are detected.

  # Kafka Configuration for Event Streaming
  kafka:
    bootstrap_servers:
      - "kafka-broker-1:9092"
      - "kafka-broker-2:9092"
      - "kafka-broker-3:9092"
    
    topics:
      # Input topics for provider metrics
      provider_metrics_input: "provider.metrics.raw"
      symbiosis_scores_input: "provider.symbiosis.scores"
      
      # Output topics for detected risks
      risk_events_output: "meta-salvage.risk.events"
      alerts_output: "meta-salvage.alerts"
    
    consumer_group: "meta-salvage-monitoring-group"
    
    configuration:
      auto_offset_reset: "latest"
      enable_auto_commit: true
      session_timeout_ms: 30000

  # Apache Flink Stream Processing
  flink:
    job_manager:
      replicas: 1
      cpu: "1000m"
      memory: "2Gi"
    
    task_manager:
      replicas: 3
      cpu: "2000m"
      memory: "4Gi"
      slots_per_task_manager: 2
    
    processing_pipelines:
      # Pipeline 1: Real-time Metric Analysis
      - name: "metric-analyzer"
        source: "provider.metrics.raw"
        operations:
          - type: "window"
            window_type: "tumbling"
            size: "60s"
          
          - type: "aggregate"
            functions:
              - avg_latency: "AVG(latency_ms)"
              - max_latency: "MAX(latency_ms)"
              - avg_throughput: "AVG(throughput_ops_sec)"
              - min_availability: "MIN(availability_pct)"
          
          - type: "filter"
            condition: >
              avg_latency > 100 OR 
              max_latency > 200 OR 
              min_availability < 99.0
          
          - type: "map"
            transformation: "create_risk_event"
        
        sink: "meta-salvage.risk.events"
      
      # Pipeline 2: Symbiosis Score Monitoring
      - name: "symbiosis-monitor"
        source: "provider.symbiosis.scores"
        operations:
          - type: "keyBy"
            field: "provider_id"
          
          - type: "window"
            window_type: "sliding"
            size: "5m"
            slide: "1m"
          
          - type: "process"
            function: "detect_symbiosis_decline"
            parameters:
              threshold_min: 0.75
              decline_rate_threshold: 0.10
          
          - type: "filter"
            condition: "risk_detected == true"
        
        sink: "meta-salvage.risk.events"
      
      # Pipeline 3: Anomaly Detection
      - name: "anomaly-detector"
        source: "provider.metrics.raw"
        operations:
          - type: "keyBy"
            field: "provider_id"
          
          - type: "window"
            window_type: "session"
            gap: "5m"
          
          - type: "process"
            function: "statistical_anomaly_detection"
            parameters:
              method: "zscore"
              threshold: 3.0
              metrics:
                - "latency_ms"
                - "cost_per_operation"
                - "throughput_ops_sec"
        
        sink: "meta-salvage.alerts"

  # Prometheus Monitoring Configuration
  prometheus:
    scrape_interval: 30s
    evaluation_interval: 30s
    
    scrape_configs:
      # CaaS Provider Metrics
      - job_name: "caas-providers"
        metrics_path: "/metrics"
        static_configs:
          - targets:
            - "provider-1.caas.internal:9090"
            - "provider-2.caas.internal:9090"
            - "provider-3.caas.internal:9090"
        
        relabel_configs:
          - source_labels: [__address__]
            target_label: provider_id
            regex: "(.*)\\.caas\\.internal.*"
            replacement: "$1"
      
      # Meta Salvage Internal Metrics
      - job_name: "meta-salvage"
        metrics_path: "/metrics"
        static_configs:
          - targets:
            - "risk-monitor:9091"
            - "decision-engine:9092"
            - "peace-bonds-manager:9093"
    
    # Alert Rules (integrated with prometheus-alerts.yaml)
    rule_files:
      - "/etc/prometheus/rules/meta-salvage-alerts.yaml"

  # Risk Detection Rules
  risk_detection:
    rules:
      - name: "symbiosis_decline"
        type: "threshold"
        metric: "symbiosis_score"
        condition: "< 0.75"
        severity: "high"
        action: "trigger_peace_bond"
      
      - name: "latency_manipulation"
        type: "rate_of_change"
        metric: "latency_ms"
        threshold: 0.25  # 25% increase
        window: "5m"
        severity: "medium"
        action: "issue_warning"
      
      - name: "cost_spike"
        type: "rate_of_change"
        metric: "cost_per_operation"
        threshold: 0.20  # 20% increase
        window: "10m"
        severity: "medium"
        action: "monitor_closely"
      
      - name: "lock_in_attempt"
        type: "pattern"
        indicators:
          - "proprietary_api_usage_increase"
          - "data_export_restrictions"
          - "migration_cost_increase"
        severity: "critical"
        action: "suspend_provider"

  # Integration with RiskMonitor
  integration:
    risk_monitor:
      endpoint: "http://risk-monitor-service:8080"
      api_version: "v1"
      
      event_forwarding:
        enabled: true
        batch_size: 100
        batch_timeout: "10s"
      
      callbacks:
        on_risk_detected: "/api/v1/risks/detected"
        on_alert_triggered: "/api/v1/alerts/trigger"

  # Data Retention Policies
  retention:
    raw_metrics: "7d"
    aggregated_metrics: "30d"
    risk_events: "90d"
    alerts: "180d"

  # Monitoring Health Checks
  health_checks:
    - name: "kafka_connectivity"
      interval: "60s"
      timeout: "10s"
    
    - name: "flink_jobs_running"
      interval: "30s"
      timeout: "5s"
    
    - name: "prometheus_scraping"
      interval: "60s"
      timeout: "10s"
